POST http://localhost/api/checkPassword
Host: localhost
Content-Type: application/json
Content-Length:  


{ 
    "name": "",
    "email": "emaildeprueba12@ep.com",
    "password": "pruebaContraseña"
}