POST http://localhost/api/checkPassword
Host: localhost
Content-Type: application/json
Content-Length:  


{ 
    "name": "",
    "email": "emaildeprueba@docker.io",
    "password": "pruebaContraseña"
}