POST http://localhost/api/createNewUser
Host: localhost
Content-Type: application/json
Content-Length:  


{
    "name": "alberto", 
    "password": "pruebaContraseña",
    "email": "emaildeprueba12@ep.com"
}

