POST http://127.0.0.1/api/sendTransaction
Host: localhost
Content-Type: application/json
Content-Length: 

{  
    "email": "marquitos@marquitos.marquitos",
    "to": "0xD1D6ADE2edFe459266671d78caE3CA99fd6861e8",
    "amount": 0.05
}

