apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: database
    role: leader
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        role: leader
        tier: backend
    spec:
      containers:
      - name: database
        image: "albertoarostegui/backend"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5432