apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: pvc-db
      containers:
      - name: database
        image: "albertoarostegui/backend"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: db-storage
            mountPath: "var/lib/postgresql/data/pgdata"
            
        ports:
        - containerPort: 5432